# This is a basic workflow to help you get started with Actions

name: PR sync
permissions: 
  contents: write
  issues: read
  actions: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Sync
        run: |
          gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"' > pr_list.txt
          while read pr head_ref; do
            echo "Triggering workflow for PR #$pr with head ref $head_ref"
            run_id=$(gh run list --branch $head_ref --json databaseId -q '.[0].databaseId')
            echo "Rerunning workflow $run_id"
            if [ -n "$run_id" ]; then
              gh run rerun $run_id
            fi
          done < pr_list.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     

